name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install tools
      run: make setup-tools
    - name: Run cyclometric complexity check
      run: |
        gocyclo -avg .
        gocyclo -over 15 .
    - name: Run cognitive complexity check
      run: |
        gocognit -avg .
        gocognit -over 15 .
    - name: Run static check
      run: staticcheck ./...
    - name: Test
      run: go test -timeout 10s -count=1 -race ./...
